// Project/Buoi23_ReactJS/react-newbie/src/DressingRoom/ProductItem.jsx
import React, { Component } from 'react'

export default class ProductItem extends Component {
    render() {
        return (
            <div className="card mb-3">
                <img src={this.props.img} alt=""/>
                <div className="card-body">
                    <p className="lead">{this.props.name}</p>
                    <button className="btn btn-success">Thử</button>
                </div>
            </div>
        )
    }
}

// Document/Buoi_27/19-06-2021-02-25-48-dressing-room-service-(1)/dressing-room-service/product-item/product-item.component.ts
import { Component, OnInit  } from '@angular/core';

@Component({
  selector: 'app-product-item',
  templateUrl: './product-item.component.html',
  styleUrls: ['./product-item.component.scss'],
})
export class ProductItemComponent implements OnInit {

  constructor() {}




  ngOnInit(): void {}
}

<div class="card mb-3">
  <img src="" />
  <div class="card-body">
    <p class="lead">Áo sơmi</p>
    <button  class="btn btn-success">Thử</button>
  </div>
</div>
