// Project/Buoi36_Angular/AngularProject/src/app/Exe1/ex1-home/home.component.ts
import { Component } from "@angular/core"

@Component({
    selector:"app-ex1-home",
    templateUrl:"./home.component.html",
    styleUrls:["./home.component.scss"],
})

export class Ex1Home {

}
<app-ex1-header></app-ex1-header>
<div class="flex">
    <app-ex1-content></app-ex1-content>
    <app-ex1-sidebar></app-ex1-sidebar>
</div>
<app-ex1-footer></app-ex1-footer>

// Project/Buoi23_ReactJS/react-newbie/src/Ex1/home.js
import React, { Component } from 'react'
import Header from './header'
import SideBar from './sideBar'
import Content from './content'
import Footer from './footer'
import './home.css'

export default class Home extends Component {
    render() {
        return (
            <div className="home">
                <Header></Header>
                <div className="home-body">
                    <SideBar></SideBar>
                    <Content></Content>
                </div>
                <Footer></Footer>
            </div>
        )
    }
}
